const foodPic = [{
    name:'Pizza',
    image:'./FoodPics/pizzaPic.avif'
},
{
    name:'Burger',
    image:'./FoodPics/burgerPic.avif'
},
{
    name:'Briyani',
    image:'./FoodPics/briyaniPic.avif'
},
{
    name:'Rolls',
    image:'./FoodPics/rollspic.avif'
},
{
    name:'Cake',
    image:'./FoodPics/cakePicc.avif'
},
{
    name:'Chicken',
    image:'./FoodPics/webPic.webP'
},
{
    name:'Thali',
    image:'./FoodPics/ThaliPic.avif'
},
{
    name:'North Indian',
    image:'./FoodPics/NorthIndianpic.avif'
},
{
    name:'Momos',
    image:'./FoodPics/MomosPic.avif'
},
{
    name:'Noodles',
    image:'./FoodPics/NoodlesPic.avif'
},
{
    name:'Dosa',
    image:'./FoodPics/DosaPic.avif'
},
{
    name:'Paneer',
    image:'./FoodPics/PaneerPic.avif'
}
]